// glossary.js – beginner-friendly Italian -> English hints used by dialogue UI.
// Keep entries A1-A2 and focused on words that appear in lessons/dialogues.

export const GLOSSARY = {
  // ── Greetings & basics ────────────────────────────────────────────────
  "buongiorno": "good morning",
  "ciao": "hi / hello",
  "grazie": "thank you",
  "per favore": "please",
  "si": "yes",
  "sì": "yes",
  "no": "no",
  "forse": "maybe",
  "scusa": "sorry / excuse me",
  "mille": "a thousand",
  "presto": "soon",
  "bene": "well / good",
  "va bene": "okay / all right",
  "buona": "good (f.)",
  "buono": "good (m.)",
  "brava": "clever / good (f.)",

  // ── Articles & prepositions ───────────────────────────────────────────
  "il": "the (m.)",
  "la": "the (f.)",
  "lo": "the (m.)",
  "le": "the (f. pl.)",
  "i": "the (m. pl.)",
  "gli": "the (m. pl.)",
  "l": "the",
  "un": "a / one",
  "una": "a / one (f.)",
  "uno": "a / one (m.)",
  "di": "of",
  "del": "of the",
  "della": "of the (f.)",
  "dell": "of the",
  "degli": "of the (pl.)",
  "agli": "to the (m. pl.)",
  "dal": "from the",
  "dalla": "from the (f.)",
  "a": "to / at",
  "al": "to the",
  "alla": "to the (f.)",
  "in": "in",
  "nel": "in the",
  "nell": "in the",
  "nella": "in the (f.)",
  "nei": "in the (pl.)",
  "con": "with",
  "da": "from / by",
  "su": "on",
  "sul": "on the",
  "sulla": "on the (f.)",
  "sull": "on the",
  "per": "for",
  "tra": "between / among",
  "e": "and / is",
  "è": "is",
  "o": "or",
  "che": "that / which / what",
  "chi": "who",
  "come": "how / as / like",
  "dove": "where",
  "quando": "when",
  "quanto": "how much",
  "qual": "which",
  "cosa": "thing / what",

  // ── Pronouns ──────────────────────────────────────────────────────────
  "io": "I",
  "tu": "you",
  "lui": "he / him",
  "lei": "she / her / you (formal)",
  "noi": "we",
  "mi": "me / to me",
  "ti": "you / to you",
  "ci": "us / there",
  "te": "you (emphasis)",
  "me": "me (emphasis)",
  "questo": "this (m.)",
  "questa": "this (f.)",
  "questi": "these (m.)",
  "queste": "these (f.)",
  "quello": "that (m.)",
  "quella": "that (f.)",
  "quel": "that (m.)",
  "quell": "that",

  // ── Common adverbs & conjunctions ─────────────────────────────────────
  "non": "not",
  "ma": "but",
  "se": "if",
  "anche": "also / too",
  "solo": "only",
  "sempre": "always",
  "mai": "never",
  "già": "already",
  "gia": "already",
  "molto": "very / much",
  "molti": "many",
  "troppo": "too much",
  "poco": "little / few",
  "quasi": "almost",
  "ancora": "still / again",
  "ora": "now",
  "adesso": "now",
  "subito": "immediately / right away",
  "qui": "here",
  "quindi": "therefore / so",
  "allora": "then / so",
  "proprio": "really / exactly",
  "davvero": "really",

  // ── Time & sequence ───────────────────────────────────────────────────
  "prima": "first / before",
  "poi": "then",
  "dopo": "after",
  "oggi": "today",
  "ieri": "yesterday",
  "domani": "tomorrow",
  "mattina": "morning",
  "giorni": "days",
  "giorno": "day",
  "anni": "years",
  "volta": "time / once",
  "volte": "times",
  "circa": "about / approximately",
  "venti": "twenty",
  "tre": "three",
  "sei": "six / you are",
  "due": "two",

  // ── Places & nouns ────────────────────────────────────────────────────
  "pane": "bread",
  "mercato": "market",
  "piazza": "square",
  "osteria": "tavern / osteria",
  "biblioteca": "library",
  "archivio": "archive",
  "documento": "document",
  "documenti": "documents",
  "pagina": "page",
  "ricetta": "recipe",
  "segreto": "secret",
  "firma": "signature",
  "famiglia": "family",
  "nome": "name",
  "parola": "word",
  "parole": "words",
  "parola chiave": "keyword",
  "carta": "card",
  "ingresso": "entrance",
  "città": "city",
  "citta": "city",
  "bologna": "Bologna",
  "bolognese": "Bolognese",
  "roma": "Rome",
  "posto": "place",
  "casa": "house / home",
  "storia": "story / history",
  "storico": "historical",
  "storici": "historical (pl.)",
  "tradizione": "tradition",
  "luce": "light",
  "nota": "note",
  "riga": "line / row",
  "lista": "list",
  "persona": "person",
  "persone": "people",
  "gente": "people",
  "salaborsa": "Salaborsa (library name)",
  "scaffale": "shelf",
  "regole": "rules",
  "accesso": "access",
  "fascicolo": "dossier / file",
  "calligrafia": "handwriting",
  "inchiostro": "ink",
  "lente": "magnifying glass / lens",
  "mistero": "mystery",
  "quadro": "picture / framework",
  "caso": "case",
  "parte": "part",
  "testi": "texts",
  "fonti": "sources",
  "fonte": "source",
  "testimone": "witness",
  "testimonianze": "testimonies",
  "voce": "voice",
  "ordine": "order",
  "differenza": "difference",
  "punto": "point",
  "livello": "level",
  "senso": "sense / meaning",
  "sigla": "initials / acronym",
  "opera": "work / creation",
  "margine": "margin",
  "guida": "guide",
  "struttura": "structure",
  "formulazione": "wording",
  "dettaglio": "detail",
  "dettagli": "details",
  "contesto": "context",
  "varianti": "variants",
  "versione": "version",
  "versioni": "versions",
  "informazione": "information",
  "nodo": "knot / issue",
  "avviso": "warning / notice",
  "prova": "proof / evidence",

  // ── Food & cooking ────────────────────────────────────────────────────
  "cipolla": "onion",
  "carota": "carrot",
  "sedano": "celery",
  "carne": "meat",
  "latte": "milk",
  "ragu": "ragù (meat sauce)",
  "ragù": "ragù (meat sauce)",
  "fuoco": "heat / flame",
  "fuoco basso": "low heat",
  "tempo": "time",
  "ore": "hours",
  "festa": "celebration / holiday",
  "soffritto": "soffritto (sautéed base)",
  "pancetta": "pancetta (cured pork belly)",
  "guanciale": "guanciale (cured pork cheek)",
  "pomodoro": "tomato",
  "conserva": "preserve / canned",
  "vino": "wine",
  "bianco": "white",
  "verdure": "vegetables",
  "vegetale": "vegetable",
  "sugo": "sauce",
  "ingrediente": "ingredient",
  "ingredienti": "ingredients",
  "cucina": "kitchen / cooking",
  "cuochi": "cooks",
  "taglio": "cut",
  "base": "base",
  "sapore": "flavor",
  "sapori": "flavors",
  "dolcezza": "sweetness",
  "acido": "acid / acidic",
  "rosolatura": "browning / searing",
  "equilibrio": "balance",
  "tempi": "times / timing",
  "minuti": "minutes",
  "minuto": "minute",
  "minimo": "minimum",
  "risultato": "result",
  "gusto": "taste",
  "appunti": "notes / jottings",
  "profilo": "profile",
  "fretta": "haste / rush",

  // ── Adjectives ────────────────────────────────────────────────────────
  "diverso": "different",
  "diversa": "different (f.)",
  "diverse": "different (f. pl.)",
  "uguale": "same",
  "piu": "more",
  "meno": "less",
  "grande": "big",
  "piccolo": "small",
  "piccola": "small (f.)",
  "piccoli": "small (pl.)",
  "lungo": "long",
  "lunga": "long (f.)",
  "nuovo": "new (m.)",
  "nuova": "new (f.)",
  "vecchio": "old (m.)",
  "vecchi": "old (m. pl.)",
  "stesso": "same (m.)",
  "stessa": "same (f.)",
  "altro": "other (m.)",
  "altra": "other (f.)",
  "altre": "other (f. pl.)",
  "altri": "other (m. pl.)",
  "ogni": "every",
  "tutto": "everything / all",
  "tutti": "everyone / all (pl.)",
  "tutta": "all (f.)",
  "tutte": "all (f. pl.)",
  "tanto": "so much",
  "tanti": "so many",
  "tante": "so many (f.)",
  "certo": "certain / sure",
  "certamente": "certainly",
  "vero": "true / real",
  "fresco": "fresh",
  "ricco": "rich",
  "lento": "slow",
  "lenta": "slow (f.)",
  "lenti": "slow (pl.)",
  "leggera": "light (f.)",
  "basso": "low",
  "bassissimo": "very low",
  "chiaro": "clear",
  "chiara": "clear (f.)",
  "chiari": "clear (pl.)",
  "chiaramente": "clearly",
  "importante": "important",
  "importanti": "important (pl.)",
  "importantissima": "very important (f.)",
  "antica": "ancient (f.)",
  "antico": "ancient (m.)",
  "nascosto": "hidden (m.)",
  "nascosta": "hidden (f.)",
  "morbido": "soft",
  "pulito": "clean",
  "corta": "short (f.)",
  "semplici": "simple (pl.)",
  "simile": "similar",
  "strano": "strange",
  "stabile": "stable",
  "coerente": "consistent",
  "coerenti": "consistent (pl.)",
  "affidabile": "reliable",
  "autentico": "authentic",
  "originale": "original",
  "speciale": "special",
  "speciali": "special (pl.)",
  "famoso": "famous",
  "nervoso": "nervous",
  "ultimo": "last (m.)",
  "ultima": "last (f.)",
  "primo": "first (m.)",
  "seconda": "second (f.)",
  "secondo": "second / according to",
  "finale": "final",
  "valida": "valid (f.)",
  "giusta": "right / correct (f.)",
  "giusto": "right / correct (m.)",
  "sicura": "sure (f.)",
  "sicuro": "sure (m.)",
  "obbligatorio": "mandatory",
  "facoltativo": "optional",
  "rigido": "strict",
  "forte": "strong",
  "utile": "useful",
  "raro": "rare",
  "illeggibile": "illegible",
  "sbiadita": "faded (f.)",
  "sbiadito": "faded (m.)",
  "cancellata": "erased (f.)",
  "scritta": "written (f.)",
  "scritti": "written (pl.)",
  "scritto": "written (m.)",
  "discusso": "debated / discussed",
  "confermato": "confirmed",
  "indeciso": "undecided",
  "dubbioso": "doubtful",
  "allineate": "aligned (f. pl.)",
  "adatto": "suitable",
  "legata": "linked / tied",
  "interessante": "interesting",
  "leggendario": "legendary",
  "normali": "normal (pl.)",
  "quotidiano": "daily",

  // ── Verbs (infinitives) ───────────────────────────────────────────────
  "capire": "to understand",
  "cercare": "to look for",
  "trovare": "to find",
  "parlare": "to speak",
  "chiedere": "to ask",
  "aiutare": "to help",
  "entrare": "to enter",
  "aprire": "to open",
  "aggiungere": "to add",
  "ricordare": "to remember",
  "leggere": "to read",
  "essere": "to be",
  "fare": "to do / to make",
  "dare": "to give",
  "dire": "to say / to tell",
  "vedere": "to see",
  "cambiare": "to change",
  "cambia": "changes",
  "cambiano": "they change",
  "cambio": "I change",
  "confermare": "to confirm",
  "confrontare": "to compare",
  "verificare": "to verify",
  "ripetere": "to repeat",
  "bollire": "to boil",
  "tremare": "to tremble",
  "unire": "to unite / to combine",
  "sciogliere": "to untie / to solve",

  // ── Conjugated verbs (essere / avere) ─────────────────────────────────
  "sono": "I am / they are",
  "è": "is",
  "era": "was",
  "siamo": "we are",
  "stato": "been",
  "ho": "I have",
  "ha": "has",
  "hai": "you have",
  "hanno": "they have",
  "avevo": "I had",

  // ── Conjugated verbs (common) ─────────────────────────────────────────
  "posso": "can I / I can",
  "puo": "can (he/she)",
  "puoi": "you can",
  "possiamo": "we can",
  "vorrei": "I would like",
  "voglio": "I want",
  "vuoi": "you want",
  "vuole": "wants",
  "vuol": "wants",
  "devo": "I must",
  "deve": "must",
  "devi": "you must",
  "fa": "does / makes / ago",
  "fai": "you do / you make",
  "faccio": "I do / I make",
  "vai": "you go / go!",
  "vado": "I go",
  "sa": "knows",
  "sembra": "seems",
  "sembrano": "they seem",
  "dice": "says",
  "dico": "I say",
  "dici": "you say",
  "diceva": "used to say",
  "dicevi": "you used to say",
  "dicono": "they say",
  "parla": "speaks / speak!",
  "parlano": "they speak",
  "parlava": "used to speak",
  "parlo": "I speak",
  "cerca": "looks for",
  "cerchi": "you look for",
  "cerco": "I look for",
  "capisco": "I understand",
  "capisci": "you understand",
  "capito": "understood",
  "serve": "is needed / serves",
  "servono": "are needed",
  "servito": "served",
  "conosco": "I know",
  "esiste": "exists",
  "esistono": "they exist",
  "usa": "uses",
  "usano": "they use",
  "uso": "I use",
  "arriva": "arrives",
  "arrivare": "to arrive",
  "torna": "come back / return!",
  "torno": "I return",
  "trova": "finds",
  "trovato": "found",
  "trovi": "you find",
  "manca": "is missing",
  "resta": "remains",
  "restava": "remained",
  "resto": "rest / I remain",
  "sento": "I hear / I feel",
  "sentito": "heard",
  "sentiva": "used to hear",
  "pensa": "thinks",
  "pensi": "you think",
  "penso": "I think",
  "spiega": "explains",
  "scrivi": "you write / write!",
  "scriveva": "used to write",
  "chiedi": "ask!",
  "chiedo": "I ask",
  "cercavi": "you were looking for",
  "cercavamo": "we were looking for",
  "chiudere": "to close",
  "chiudi": "close!",
  "aggiungi": "add!",
  "aggiungo": "I add",
  "aggiunge": "adds",
  "esagera": "exaggerates",
  "esagerando": "exaggerating",
  "inizia": "start! / begins",
  "coincide": "matches / coincides",
  "contraddice": "contradicts",
  "concordano": "agree",
  "conferma": "confirms / confirm!",
  "confermano": "they confirm",
  "confermata": "confirmed (f.)",
  "confermi": "you confirm",
  "conferme": "confirmations",
  "segnala": "report / flag!",
  "segno": "I note / sign",
  "perde": "loses",
  "sbaglia": "is wrong",
  "sorprende": "surprises",
  "dipende": "depends",
  "suggerisce": "suggests",
  "appesantisce": "weighs down",
  "precisa": "clarifies / precise",
  "registro": "I note / I register",
  "visto": "seen",
  "sfumo": "I deglaze",
  "rosoli": "you brown / sear",
  "contiene": "contains",
  "raccolta": "collected / collection",
  "raccolto": "collected",
  "lavorato": "worked",
  "controllato": "checked",
  "leggiamo": "we read / let's read",
  "scegli": "choose!",
  "letto": "read (past)",
  "messo": "put / placed",
  "portamelo": "bring it to me",
  "spiegami": "explain to me",
  "spiegarti": "to explain to you",
  "aiutarti": "to help you",
  "chiederti": "to ask you",
  "ricontrollato": "re-checked",
  "accedervi": "to access it",
  "leggerla": "to read it",
  "vederlo": "to see it",
  "vederti": "to see you",
  "adattarla": "to adapt it",
  "dirmelo": "to tell me it",
  "segnarlo": "to mark it",
  "guardato": "looked at",
  "guarda": "look!",
  "abbiamo": "we have",
  "pensarla": "to think about it",

  // ── Expressions & common phrases ──────────────────────────────────────
  "un poco di": "a little bit of",
  "alla fine": "at the end",
  "niente": "nothing",
  "abbastanza": "enough",
  "finalmente": "finally",
  "esattamente": "exactly",
  "esatto": "exactly / that's right",
  "perfetto": "perfect",
  "ottimo": "excellent",
  "cosi": "so / like this",
  "conto": "account / on my own",
  "serio": "serious",
  "assolutamente": "absolutely",
  "certo": "sure / of course",
  "calma": "calm",
  "piano": "slowly / softly",
  "basta": "enough / that's enough",
  "bastano": "are enough",
  "almeno": "at least",
  "cento": "hundred",
  "spesso": "often",
  "insieme": "together",
  "dietro": "behind",
  "sotto": "under / below",
  "davvero": "really",
  "soprattutto": "above all",
  "sola": "alone (f.)",
  "solo": "alone / only",
  "stai": "you are (state)",
  "sto": "I am (state)",
  "ci mancherebbe": "of course / not at all",
  "ragione": "reason / right",
  "nemici": "enemies",
  "esplorando": "exploring",
  "dubbi": "doubts",
  "dubbio": "doubt",
  "domanda": "question",
  "domande": "questions",
  "scelta": "choice",
  "passaggio": "step / passage",
  "lettura": "reading",
  "detto": "said",
  "fatto": "done / made",
  "il fatto suo": "her/his stuff",
  "sparito": "disappeared",
  "lavoro": "work",
  "verifica": "verification",
  "verifiche": "verifications",
  "chiarimento": "clarification",
  "riepilogo": "summary",
  "conferma registrata": "confirmation recorded",
  "identita": "identity",
  "significato": "meaning",
  "significa": "means",
  "flessibilita": "flexibility",
  "pazienza": "patience",
  "stavolta": "this time",

  // ── Connector words seen in dialogues ─────────────────────────────────
  "c": "(contraction fragment)",
  "d": "(contraction fragment)",
  "l": "the (contraction)",
  "f": "(abbreviation)",
  "m": "(abbreviation)",
  "che cosa": "what?",
  "c'e": "there is",
  "non mi sorprende": "it doesn't surprise me",
  "corro": "I run",
  "vivo": "I live / alive",
  "vive": "living / alive (pl.)",

  // ── Additional common words from dialogues ────────────────────────────
  "accordo": "agreement",
  "aiuto": "help",
  "anch": "also (contraction of anche)",
  "attimo": "moment",
  "chiave": "key",
  "chiusa": "closed (f.)",
  "chiuso": "closed (m.)",
  "citano": "they cite / mention",
  "compro": "I buy",
  "cose": "things",
  "direi": "I would say",
  "diversamente": "differently",
  "dobbiamo": "we must",
  "fine": "end",
  "fosse": "were (subjunctive)",
  "funziona": "works / functions",
  "giro": "around / tour",
  "idea": "idea",
  "mancherebbe": "would be missing",
  "manda": "sends",
  "mano": "hand",
  "meglio": "better",
  "messaggio": "message",
  "metodo": "method",
  "mia": "my (f.)",
  "mio": "my (m.)",
  "migliore": "better / best",
  "migliori": "better / best (pl.)",
  "nasconda": "is hiding (subjunctive)",
  "nasconde": "hides",
  "nessuno": "nobody",
  "nonna": "grandmother",
  "nonno": "grandfather",
  "ottiene": "obtains",
  "parlarne": "to talk about it",
  "parlato": "spoken / talked",
  "parti": "leave! / you leave",
  "vicini": "nearby / close (pl.)",
  "perche": "why / because",
  "piatti": "dishes / plates",
  "po": "a bit (un po')",
  "poche": "few (f.)",
  "porta": "brings / door",
  "potrebbe": "could",
  "potrei": "I could",
  "pratica": "practice",
  "indicazione": "indication / direction",
  "pronta": "ready (f.)",
  "pronti": "ready (m. pl.)",
  "pubblico": "public",
  "pure": "also / go ahead",
  "qualcosa": "something",
  "qualcuno": "someone",
  "registrata": "recorded (f.)",
  "dato": "given / data",
  "ricordo": "I remember / memory",
  "riuscivo": "I could / I managed",
  "smentita": "denial / rebuttal",
  "suo": "his / her",
  "tua": "your (f.)",
  "uniscono": "they unite / blend",
  "va": "goes",
  "vedi": "you see / see!",

  // ── Chapter 1 finale (quests 21-30) vocabulary ───────────────────────
  "abbinamento": "pairing / match",
  "aspetta": "wait!",
  "aspetto": "I wait / appearance",
  "alzi": "you raise / raise!",
  "armonico": "harmonious",
  "asciuga": "dries",
  "attesa": "waiting",
  "autentica": "authentic (f.)",
  "biglietto": "ticket",
  "brodo": "broth",
  "capitolo": "chapter",
  "carattere": "character",
  "chiudersi": "to close (itself)",
  "chiusura": "closure",
  "confermo": "I confirm",
  "conta": "counts / matters",
  "continua": "continues",
  "corre": "runs",
  "corretto": "correct",
  "cottura": "cooking",
  "deciso": "decided",
  "dieci": "ten",
  "definisce": "defines",
  "diventa": "becomes",
  "dolce": "sweet / gentle",
  "dosato": "measured / dosed",
  "ecco": "here is",
  "fiamma": "flame",
  "formula": "formula",
  "fresche": "fresh (f. pl.)",
  "fondo": "bottom / base",
  "larga": "wide (f.)",
  "milano": "Milan",
  "misure": "measurements",
  "pentola": "pot",
  "partiro": "I will leave",
  "pesante": "heavy",
  "porto": "I bring",
  "principio": "principle",
  "quaderno": "notebook",
  "regola": "rule",
  "restare": "to remain",
  "rifinire": "to finish / refine",
  "ritmo": "rhythm / pace",
  "ricostruito": "reconstructed",
  "riposo": "rest",
  "rotondo": "round / rounded",
  "rompi": "you break / break!",
  "senza": "without",
  "semplice": "simple",
  "spegni": "turn off!",
  "spaghetti": "spaghetti",
  "tagliatelle": "tagliatelle",
  "tecnica": "technique",
  "tengono": "they hold",
  "uniforme": "uniform / even",
  "viaggio": "journey / trip",

  // ── NPC names (so hover doesn't show 'not in glossary') ───────────────
  "marco": "Marco (NPC name)",
  "lucia": "Lucia (NPC name)",
  "giorgio": "Giorgio (NPC name)",
  "elena": "Elena (NPC name)",
  "donna": "lady / Mrs.",
  "rosa": "Rosa (NPC name) / pink",
  "bianchi": "Bianchi (surname) / white (pl.)",
  "ferrante": "Ferrante (surname)",
  "neri": "Neri (surname) / black (pl.)",
  "conti": "Conti (surname) / counts",
  "maria": "Maria (name)",
  "faro": "I will do",
  "ferma": "stops / still",

  // ── Shop & idle dialogue vocabulary ─────────────────────────────────────
  "appetito": "appetite",
  "apre": "opens",
  "assaggiare": "to taste / to try",
  "bellissime": "very beautiful (f. pl.)",
  "bicchiere": "glass (drinking)",
  "caldo": "hot / warm",
  "cornetto": "croissant",
  "costa": "costs",
  "crema": "cream / custard",
  "cucino": "I cook",
  "delicati": "delicate (pl.)",
  "dispiace": "sorry / to be sorry",
  "disturbare": "to disturb / to bother",
  "dorme": "sleeps",
  "esercizio": "exercise",
  "espresso": "espresso",
  "focaccia": "focaccia (flatbread)",
  "freschissime": "very fresh (f. pl.)",
  "freschissimo": "very fresh (m.)",
  "giornata": "day (the whole day)",
  "impara": "learns",
  "imparando": "learning",
  "lontano": "far / far away",
  "mangiato": "eaten",
  "mani": "hands",
  "mele": "apples",
  "moneta": "coin",
  "nascondono": "they hide",
  "olive": "olives",
  "organizzato": "organized",
  "panetteria": "bakery",
  "panino": "sandwich / roll",
  "pieno": "full",
  "pomeriggio": "afternoon",
  "porte": "doors",
  "prendi": "you take / you have (ordering)",
  "prosciutto": "ham (cured)",
  "pulite": "clean (pl.)",
  "purtroppo": "unfortunately",
  "qualche": "some / a few",
  "ricaricare": "to recharge",
  "richiede": "requires",
  "scaffali": "shelves",
  "scoprire": "to discover",
  "segreti": "secrets",
  "seria": "serious (f.)",
  "soldi": "money",
  "solito": "usual",
  "spesa": "shopping / groceries",
  "studiando": "studying",
  "tranquilla": "quiet / calm (f.)",
  "tuo": "your (m.)",
  "venuto": "come (past participle)",
  "ehilà": "hey there",
  "bentornato": "welcome back",
  "eccellente": "excellent",
  "ottima": "excellent / great (f.)",
  "perfetto": "perfect"
};

